# browser_emulator.py — Browser Emulator representing a bot client environment

import random
from browser_fingerprints import BROWSER_FINGERPRINTS

class BrowserEmulator:
    def __init__(self, profile):
        """
        profile: A dict generated by DeviceManager.sample_profile()
        """
        self.profile = profile
        self._browser_type = profile["browser_type"]
        self._device_type = profile["device_type"]
        self._os_type = profile["os_type"]
        self.fingerprint = self.generate_fingerprint()

    @property
    def browser_type(self):
        return self._browser_type

    @property
    def device_type(self):
        return self._device_type

    @property
    def os_type(self):
        return self._os_type

    def generate_user_agent(self):
        config = BROWSER_FINGERPRINTS.get(self.browser_type)
        if not config:
            return "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

        version = self.profile.get("browser_version_spec") or random.choice(config["versions"])
        template = config["user_agent_template"]

        # Parse OS Details
        os_details = self.profile["os_details"]
        os_version = self.profile["os_version"]
        device_model = self.profile["device_model"]

        # Format iOS version underscore
        os_version_underscore = os_version.replace(".", "_")

        try:
            ua = template.format(
                os_details=os_details,
                version=version,
                os_version=os_version,
                device_model=device_model,
                os_version_underscore=os_version_underscore
            )
            return ua
        except Exception:
            # Safe fallback if formatting fails due to missing keys in template
            return "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

    def get_screen_resolution(self):
        return self.profile["screen_resolution"]

    def get_viewport(self):
        return self.profile["viewport"]

    def get_webrtc_support(self):
        config = BROWSER_FINGERPRINTS.get(self.browser_type, {})
        return {
            "webrtc_implementation": config.get("webrtc_implementation", "Standard WebRTC"),
            "simulcast_layers": config.get("simulcast_layers", 1),
            "adaptive_bitrate": config.get("adaptive_bitrate", True),
            "codecs": config.get("codecs", ["VP8", "H264"])
        }

    def get_codec_preferences(self):
        config = BROWSER_FINGERPRINTS.get(self.browser_type, {})
        return config.get("codecs", ["VP8", "H264"])

    def generate_fingerprint(self):
        """
        Creates a dictionary of fingerprint details for action logging and reporting.
        """
        webrtc = self.get_webrtc_support()
        screen = self.get_screen_resolution()
        viewport = self.get_viewport()
        
        # Determine actual version string used
        config = BROWSER_FINGERPRINTS.get(self.browser_type, {})
        versions = config.get("versions", ["1.0"])
        version = self.profile.get("browser_version_spec") or versions[0]

        return {
            "browser_type": self.browser_type,
            "browser_name": config.get("name", self.browser_type.upper()),
            "browser_version": version,
            "browser_engine": config.get("engine", "Blink"),
            "device_type": self.device_type,
            "os_type": self.os_type,
            "os_version": self.profile.get("os_version", "1.0"),
            "user_agent": self.generate_user_agent(),
            "screen_resolution": screen,
            "viewport": viewport,
            "device_pixel_ratio": self.profile.get("device_pixel_ratio", 1.0),
            "device_model": self.profile.get("device_model", "Unknown Device"),
            "hardware_profile": self.profile.get("hardware_profile", {
                "cpu_class": "Standard CPU",
                "ram_class": "8GB",
                "gpu_class": "Standard Graphics"
            }),
            "webrtc_implementation": webrtc["webrtc_implementation"],
            "simulcast_layers": webrtc["simulcast_layers"],
            "codecs": webrtc["codecs"],
            "adaptive_bitrate": webrtc["adaptive_bitrate"]
        }
